In [2]:
%matplotlib inline
import sys 
sys.path.append('..')
from preamble import *

In [3]:
import os
# The file has no headers naming the columns, so we pass header=None
# and provide the column names explicitly in "names"
adult_path = os.path.join(mglearn.datasets.DATA_PATH, "adult.data")

data = pd.read_csv(
    adult_path, 
    header=None, 
    index_col=False,
    names=['age', 'workclass', 'fnlwgt', 'education',  'education-num',
           'marital-status', 'occupation', 'relationship', 'race', 'gender',
           'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
           'income']
)

# For illustration purposes, we only select some of the columns:
data = data[['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']]
# IPython.display allows nice output formatting within the Jupyter notebook

display(data.head())

print(data.size)

age          workclass   education   gender  hours-per-week  \
0   39          State-gov   Bachelors     Male              40   
1   50   Self-emp-not-inc   Bachelors     Male              13   
2   38            Private     HS-grad     Male              40   
3   53            Private        11th     Male              40   
4   28            Private   Bachelors   Female              40   

           occupation  income  
0        Adm-clerical   <=50K  
1     Exec-managerial   <=50K  
2   Handlers-cleaners   <=50K  
3   Handlers-cleaners   <=50K  
4      Prof-specialty   <=50K

227927


In [4]:
print(data.gender.value_counts())


 Male      21790
 Female    10771
Name: gender, dtype: int64


In [5]:
print(data.workclass.value_counts())

 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: workclass, dtype: int64


In [6]:
print("Original features:", list(data.columns))
print("length of features:", len(data.columns))

Original features: ['age', 'workclass', 'education', 'gender', 'hours-per-week', 'occupation', 'income']
length of features: 7


In [7]:
data_dummies = pd.get_dummies(data)
print("Features after get_dummies:\n", list(data_dummies.columns))
print("length of dummy features:", len(data_dummies.columns))

Features after get_dummies:
 ['age', 'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov', 'workclass_ Local-gov', 'workclass_ Never-worked', 'workclass_ Private', 'workclass_ Self-emp-inc', 'workclass_ Self-emp-not-inc', 'workclass_ State-gov', 'workclass_ Without-pay', 'education_ 10th', 'education_ 11th', 'education_ 12th', 'education_ 1st-4th', 'education_ 5th-6th', 'education_ 7th-8th', 'education_ 9th', 'education_ Assoc-acdm', 'education_ Assoc-voc', 'education_ Bachelors', 'education_ Doctorate', 'education_ HS-grad', 'education_ Masters', 'education_ Preschool', 'education_ Prof-school', 'education_ Some-college', 'gender_ Female', 'gender_ Male', 'occupation_ ?', 'occupation_ Adm-clerical', 'occupation_ Armed-Forces', 'occupation_ Craft-repair', 'occupation_ Exec-managerial', 'occupation_ Farming-fishing', 'occupation_ Handlers-cleaners', 'occupation_ Machine-op-inspct', 'occupation_ Other-service', 'occupation_ Priv-house-serv', 'occupation_ Prof-specialty', 'occupatio

In [8]:
display(data_dummies.head(n=10))

age  hours-per-week  workclass_ ?  workclass_ Federal-gov      ...       \
0   39              40             0                       0      ...        
1   50              13             0                       0      ...        
2   38              40             0                       0      ...        
3   53              40             0                       0      ...        
4   28              40             0                       0      ...        
5   37              40             0                       0      ...        
6   49              16             0                       0      ...        
7   52              45             0                       0      ...        
8   31              50             0                       0      ...        
9   42              40             0                       0      ...        

   occupation_ Tech-support  occupation_ Transport-moving  income_ <=50K  \
0                         0                             0              1   
1                         0                             0              1   
2                         0                             0              1   
3                         0                             0              1   
4                         0                             0              1   
5                         0                             0              1   
6                         0                             0              1   
7                         0                             0              0   
8                         0                             0              0   
9                         0                             0              0   

   income_ >50K  
0             0  
1             0  
2             0  
3             0  
4             0  
5             0  
6             0  
7             1  
8             1  
9             1  

[10 rows x 46 columns]

In [9]:
one_hot_encoded = data_dummies.loc[:, 'workclass_ ?':'workclass_ Without-pay']
display(one_hot_encoded.head(n=10))

workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0             0                       0                     0   
1             0                       0                     0   
2             0                       0                     0   
3             0                       0                     0   
4             0                       0                     0   
5             0                       0                     0   
6             0                       0                     0   
7             0                       0                     0   
8             0                       0                     0   
9             0                       0                     0   

   workclass_ Never-worked           ...            workclass_ Self-emp-inc  \
0                        0           ...                                  0   
1                        0           ...                                  0   
2                        0           ...                                  0   
3                        0           ...                                  0   
4                        0           ...                                  0   
5                        0           ...                                  0   
6                        0           ...                                  0   
7                        0           ...                                  0   
8                        0           ...                                  0   
9                        0           ...                                  0   

   workclass_ Self-emp-not-inc  workclass_ State-gov  workclass_ Without-pay  
0                            0                     1                       0  
1                            1                     0                       0  
2                            0                     0                       0  
3                            0                     0                       0  
4                            0                     0                       0  
5                            0                     0                       0  
6                            0                     0                       0  
7                            1                     0                       0  
8                            0                     0                       0  
9                            0                     0                       0  

[10 rows x 9 columns]

In [10]:
print(type(one_hot_encoded.values))
print(one_hot_encoded.values[:10])

<class 'numpy.ndarray'>
[[0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]]


In [11]:
# Get only the columns containing features
# that is all columns from 'age' to 'occupation_ Transport-moving'
# This range contains all the features but not the target

features = data_dummies.loc[:, 'age':'occupation_ Transport-moving']

# extract NumPy arrays
X = features.values
y = data_dummies['income_ >50K'].values
print("X.shape: {}  y.shape: {}".format(X.shape, y.shape))

X.shape: (32561, 44)  y.shape: (32561,)


In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

logreg = LogisticRegression()
logreg.fit(X_train, y_train)

print("Test score: {:.2f}".format(logreg.score(X_test, y_test)))

Test score: 0.81
